### ISSUE TITLE
Provide access to scrap ALL shows from trakt.

### ISSUE THREAD

**Issue by manfromafar** [madslundt/sonarr-pogdesign-importer#1]
Add ability to call https://api.trakt.tv/calendars/all/shows/new
to search for all shows released within a certain time span.
Will be handy if your going for every show ever 
https://trakt.docs.apiary.io/#reference/calendars/all-new-shows/get-new-shows

**Comment by madslundt** [comment]
Yes I've added it in the version 0.5.2.
The list name is 'new' and does not use minimum rating or year interval. It just uses Trakt default values as start date and days.
